// Generated by scripts/sync-shared.ts from src/match/score.ts. Do not edit: change the
// source and run `pnpm sync:shared`. A test fails if this copy drifts.

import type { IntentId, Person } from "../data/types.ts";

/**
 * Rules-based, explainable "who should I meet" scoring (PRD §6.3). Every part is 0–1; the total
 * is a weighted sum. Weights are starting values, tuned with the population simulation.
 */
export const WEIGHTS = {
  topic: 3.0,
  intent: 2.5,
  keywords: 0.8,
  wavedAtYou: 0.6,
  fresh: 0.4,
  shownBefore: -1.5,
  crowded: -0.8,
} as const;

export interface ScoreParts {
  readonly topic: number;
  readonly intent: number;
  readonly keywords: number;
  /** The most telling word both one-liners share, for the reason text. */
  readonly keyword: string | null;
  readonly wavedAtYou: number;
  readonly fresh: number;
  readonly shownBefore: number;
  readonly crowded: number;
}

export interface ScoreContext {
  readonly now: number;
  /** Decayed 0–1 per person who appeared in the viewer's recent hands. */
  readonly shownBefore: ReadonlyMap<string, number>;
  /** People who already waved at the viewer. Hidden: used for ranking, never shown. */
  readonly wavedAtViewer: ReadonlySet<string>;
  /** Pending inbound waves per candidate, to spread attention away from the crowded. */
  readonly inbound: ReadonlyMap<string, number>;
}

const FRESH_MS = 48 * 3_600_000;

/** Shared-topic weight by position: [viewer primary?][candidate primary?]. */
function positionWeight(viewerIndex: number, candidateIndex: number): number {
  return 3 - Math.min(viewerIndex, 1) - Math.min(candidateIndex, 1);
}

/** How strongly two people's topics overlap; a shared primary topic counts most. */
export function topicOverlap(viewer: Person, candidate: Person): number {
  let sum = 0;
  viewer.topics.forEach((topic, i) => {
    const j = candidate.topics.indexOf(topic);
    if (j >= 0) sum += positionWeight(i, j);
  });
  return Math.min(1, sum / 3);
}

const COMPLEMENTS: ReadonlyArray<readonly [IntentId, IntentId, number]> = [
  ["hiring", "job_hunting", 1],
  ["raising", "investing", 1],
  ["cofounder", "cofounder", 0.8],
  ["cofounder", "building", 0.6],
  ["building", "investing", 0.6],
  ["hiring", "learning", 0.5],
  ["building", "learning", 0.5],
  ["researching", "building", 0.5],
  ["researching", "researching", 0.4],
  ["learning", "researching", 0.4],
];

/** Value of one intent pair (symmetric). "Just here for chai" mixes with anyone a little. */
export function complementOf(a: IntentId, b: IntentId): number {
  for (const [x, y, value] of COMPLEMENTS) {
    if ((x === a && y === b) || (x === b && y === a)) return value;
  }
  return a === "vibing" || b === "vibing" ? 0.2 : 0;
}

/** Best complement across both people's intents, with the pair that produced it. */
export function bestComplement(
  viewer: Person,
  candidate: Person,
): { value: number; pair: readonly [IntentId, IntentId] | null } {
  let best: { value: number; pair: readonly [IntentId, IntentId] | null } = {
    value: 0,
    pair: null,
  };
  for (const a of viewer.intent) {
    for (const b of candidate.intent) {
      const value = complementOf(a, b);
      if (value > best.value) best = { value, pair: [a, b] };
    }
  }
  return best;
}

const STOPWORDS = new Set(
  (
    "the and for with that this from your you are about here what want looking build building " +
    "need let lets talk chai into over more come next love like just been have has its can will " +
    "out who how why our they them their some any all new first ask me my it is an a to of in on " +
    "at by be or as do so up we us"
  ).split(" "),
);

function keywords(lines: readonly string[]): Set<string> {
  const words =
    lines
      .join(" ")
      .toLowerCase()
      .match(/[a-z][a-z0-9]{2,}/g) ?? [];
  return new Set(words.filter((w) => !STOPWORDS.has(w)));
}

/** Jaccard overlap of meaningful one-liner words, plus the longest shared word. */
export function keywordOverlap(
  viewer: Person,
  candidate: Person,
): { value: number; word: string | null } {
  const a = keywords(viewer.oneLiners);
  const b = keywords(candidate.oneLiners);
  let word: string | null = null;
  let shared = 0;
  for (const w of a) {
    if (!b.has(w)) continue;
    shared++;
    if (!word || w.length > word.length) word = w;
  }
  const union = a.size + b.size - shared;
  return { value: union === 0 ? 0 : shared / union, word };
}

export function scoreParts(viewer: Person, candidate: Person, ctx: ScoreContext): ScoreParts {
  const words = keywordOverlap(viewer, candidate);
  const age = ctx.now - candidate.joinedAt;
  return {
    topic: topicOverlap(viewer, candidate),
    intent: bestComplement(viewer, candidate).value,
    keywords: words.value,
    keyword: words.word,
    wavedAtYou: ctx.wavedAtViewer.has(candidate.id) ? 1 : 0,
    fresh: age >= 0 && age < FRESH_MS ? 1 - age / FRESH_MS : 0,
    shownBefore: ctx.shownBefore.get(candidate.id) ?? 0,
    crowded: Math.min(1, (ctx.inbound.get(candidate.id) ?? 0) / 10),
  };
}

export function totalScore(parts: ScoreParts): number {
  return (
    WEIGHTS.topic * parts.topic +
    WEIGHTS.intent * parts.intent +
    WEIGHTS.keywords * parts.keywords +
    WEIGHTS.wavedAtYou * parts.wavedAtYou +
    WEIGHTS.fresh * parts.fresh +
    WEIGHTS.shownBefore * parts.shownBefore +
    WEIGHTS.crowded * parts.crowded
  );
}

export interface Eligibility {
  /** People you waved at, skipped (still active), share a chai with, or blocked. */
  readonly excluded: ReadonlySet<string>;
  /** Demo people count as candidates only in demo mode. */
  readonly allowDemo: boolean;
}

/** Hard exclusions (PRD §6.3): never yourself, never excluded people, demo only in demo mode. */
export function isEligible(viewer: Person, candidate: Person, rules: Eligibility): boolean {
  if (candidate.id === viewer.id || candidate.isYou) return false;
  if (rules.excluded.has(candidate.id)) return false;
  return rules.allowDemo || !candidate.isDemo;
}
