// Writes supabase/seed.sql: 1,500 demo beans with handles and ~15,000 waves across the last 3
// Meet days, from the app's own demo generator (docs/prd/database.md §14).
// Run with `pnpm db:seed`; Deno resolves the app's `@/` imports through scripts/deno.json.
import { generateDemo } from "@/data/generateDemo";
import { createRng } from "@/data/rng";
import type { Person } from "@/data/types";
import { demoWaveTarget } from "@/match/points";

const SEED = 2026;
const PEOPLE = 1500;
const WAVES = 15_000;
const DAYS = 3;
const WAVES_PER_DAY = 50;
const BATCH = 500;
const OUT = "supabase/seed.sql";

/** Stable, obviously-demo UUIDs: d0000000-0000-4000-8000-<index>. */
function uuidOf(index: number): string {
  return `d0000000-0000-4000-8000-${index.toString(16).padStart(12, "0")}`;
}

function text(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function textArray(values: readonly string[]): string {
  return values.length === 0 ? "'{}'::text[]" : `array[${values.map(text).join(",")}]`;
}

function nullable(value: string | null): string {
  return value === null ? "null" : text(value);
}

/** Splits rows into multi-row INSERT statements. */
function inserts(head: string, rows: readonly string[], tail = ""): string {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += BATCH) {
    out.push(`${head}\n${rows.slice(i, i + BATCH).join(",\n")}${tail};`);
  }
  return out.join("\n\n");
}

function personRow(p: Person, id: string, rng: ReturnType<typeof createRng>): string {
  const a = p.avatar;
  const hoursAgo = Math.round(rng.range(1, 24 * 9));
  return `(${text(id)}, 'demo', ${text(p.name)}, ${textArray(p.topics)}, ${textArray(p.intent)}, ${textArray(p.oneLiners)}, ${a.skin}, ${a.hair}, ${a.hairColor}, ${a.accessory}, ${p.telegramVerified}, ${p.ticketVerified}, now() - interval '${hoursAgo} hours')`;
}

interface Wave {
  readonly from: number;
  readonly to: number;
  readonly daysAgo: number;
  /** Minutes after that Meet day began (06:00 IST = 00:30 UTC). */
  readonly minute: number;
}

/** Bookkeeping that keeps the seed realistic: one wave per pair, 50 per waver per day. */
class WaveLedger {
  readonly waves: Wave[] = [];
  readonly points = new Map<string, number>();
  private readonly pairs = new Set<string>();
  private readonly sent = new Map<string, number>();

  /** Records the wave unless it repeats a pair or breaks the daily quota. */
  add(wave: Wave, targetId: string): boolean {
    const pair = `${wave.from}:${wave.to}`;
    const quota = `${wave.from}:${wave.daysAgo}`;
    if (wave.from === wave.to || this.pairs.has(pair)) return false;
    if ((this.sent.get(quota) ?? 0) >= WAVES_PER_DAY) return false;
    this.pairs.add(pair);
    this.sent.set(quota, (this.sent.get(quota) ?? 0) + 1);
    this.points.set(targetId, (this.points.get(targetId) ?? 0) + 1);
    this.waves.push(wave);
    return true;
  }
}

/** Who waved at whom: targets weighted like the live demo (catchy one-liners, popularity). */
function pickWaves(people: readonly Person[], rng: ReturnType<typeof createRng>): Wave[] {
  const index = new Map(people.map((p, i) => [p.id, i]));
  const ledger = new WaveLedger();
  const random = (): number => rng.next();
  for (let attempt = 0; ledger.waves.length < WAVES && attempt < WAVES * 4; attempt++) {
    const target = demoWaveTarget(people, (p) => ledger.points.get(p.id) ?? 0, random);
    if (!target) break;
    const wave: Wave = {
      from: rng.int(people.length),
      to: index.get(target.id) ?? 0,
      daysAgo: rng.int(DAYS),
      minute: rng.int(24 * 60),
    };
    ledger.add(wave, target.id);
  }
  return ledger.waves;
}

function seedSql(): string {
  const people = generateDemo({
    seed: SEED,
    count: PEOPLE,
    reserve: 0,
    now: Date.UTC(2026, 9, 1),
  }).people;
  const rng = createRng(SEED ^ 0x5eed);
  const ids = people.map((_, i) => uuidOf(i));
  const waves = pickWaves(people, rng);
  const peopleRows = people.map((p, i) => personRow(p, ids[i] as string, rng));
  const contactRows = people.map(
    (p, i) => `(${text(ids[i] as string)}, ${nullable(p.telegram)}, ${nullable(p.x)})`,
  );
  const waveRows = waves.map(
    (w) =>
      // The time is derived from the Meet day (never in the future), so the two always agree.
      `(${text(ids[w.from] as string)}, ${text(ids[w.to] as string)}, private.current_meet_day() - ${w.daysAgo}, least(now(), ((private.current_meet_day() - ${w.daysAgo})::timestamp + interval '30 minutes' + interval '${w.minute} minutes') at time zone 'UTC'))`,
  );
  return [
    "-- Generated by `pnpm db:seed` (scripts/seed.ts). Demo data only: every bean has",
    "-- source = 'demo'. Remove it all before launch with `select private.purge_demo();`.",
    "begin;",
    inserts(
      "insert into private.people (id, source, name, topics, intents, one_liners, skin, hair, hair_color, accessory, telegram_verified, ticket_verified, joined_at) values",
      peopleRows,
    ),
    inserts("insert into private.contacts (person_id, telegram, x) values", contactRows),
    inserts(
      "insert into private.waves (from_id, to_id, meet_day, created_at) values",
      waveRows,
      "\non conflict do nothing",
    ),
    `-- Mutual waves become chais.
insert into private.chais (a_id, b_id, created_at)
select w.from_id, w.to_id, greatest(w.created_at, r.created_at)
from private.waves w
join private.waves r on r.from_id = w.to_id and r.to_id = w.from_id
where w.from_id < w.to_id
on conflict do nothing;`,
    "commit;",
    "",
  ].join("\n\n");
}

const sql = seedSql();
await Deno.writeTextFile(OUT, sql);
console.log(`wrote ${OUT} (${(sql.length / 1024).toFixed(0)} KB)`);
