/**
 * The app modules the Edge Functions reuse (deal-hand builds hands with the same code as the
 * demo), and how a copy for Deno is made from each. Pure, so the drift test can use it too.
 */

/** Paths under `src/`, without extension. Order doesn't matter. */
export const SHARED_MODULES: readonly string[] = [
  "data/types",
  "data/affinity",
  "data/topics",
  "data/intents",
  "match/score",
  "match/reasons",
  "match/hand",
  "match/day",
];

/** Where a module's copy lives, relative to the repo root. */
export function sharedPath(module: string): string {
  return `supabase/functions/_shared/${module}.ts`;
}

function relativeImport(fromModule: string, toModule: string): string {
  const from = fromModule.split("/").slice(0, -1);
  const to = toModule.split("/");
  let common = 0;
  while (common < from.length && from[common] === to[common]) common++;
  const up = from.slice(common).map(() => "..");
  const path = [...up, ...to.slice(common)].join("/");
  return `${path.startsWith(".") ? path : `./${path}`}.ts`;
}

/**
 * The Deno copy of `src/<module>.ts`: a do-not-edit header, and `@/x/y` imports rewritten to
 * relative paths with `.ts` extensions (Deno doesn't resolve extensionless specifiers).
 */
export function sharedCopy(module: string, source: string): string {
  const rewritten = source.replace(/from "@\/([^"]+)"/g, (_match, target: string) => {
    if (!SHARED_MODULES.includes(target)) {
      throw new Error(`src/${module}.ts imports @/${target}, which isn't in SHARED_MODULES`);
    }
    return `from "${relativeImport(module, target)}"`;
  });
  const header =
    `// Generated by scripts/sync-shared.ts from src/${module}.ts. Do not edit: change the\n` +
    `// source and run \`pnpm sync:shared\`. A test fails if this copy drifts.\n\n`;
  return header + rewritten;
}
